// frontend/src/components/MemberForm.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { getFieldDefinitions } from '../api/fieldDefinitions'
import type { Member, MembershipType } from '../types'

const props = defineProps<{ modelValue: Partial<Member>; disabled?: boolean }>()
const emit = defineEmits<{ (e: 'update:modelValue', v: Partial<Member>): void }>()

const { data: fields } = useQuery({
  queryKey: ['field-definitions'],
  queryFn: getFieldDefinitions,
})

const cf = computed(() => (props.modelValue.custom_fields as Record<string, unknown>) ?? {})

function set(key: keyof Member, val: unknown) {
  emit('update:modelValue', { ...props.modelValue, [key]: val })
}

function setCf(name: string, val: unknown) {
  set('custom_fields', { ...cf.value, [name]: val })
}
</script>

<template>
  <el-form label-position="top">
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px">
      <el-form-item label="First Name *">
        <el-input :model-value="modelValue.first_name ?? ''"
          @update:model-value="set('first_name', $event)" :disabled="disabled" />
      </el-form-item>
      <el-form-item label="Last Name *">
        <el-input :model-value="modelValue.last_name ?? ''"
          @update:model-value="set('last_name', $event)" :disabled="disabled" />
      </el-form-item>
      <el-form-item label="Email">
        <el-input type="email" :model-value="modelValue.email ?? ''"
          @update:model-value="set('email', $event || null)" :disabled="disabled" />
      </el-form-item>
      <el-form-item label="Phone">
        <el-input :model-value="modelValue.phone ?? ''"
          @update:model-value="set('phone', $event || null)" :disabled="disabled" />
      </el-form-item>
    </div>

    <el-form-item label="Membership Type *">
      <el-select :model-value="modelValue.membership_type ?? ''"
        @update:model-value="set('membership_type', $event as MembershipType)" :disabled="disabled">
        <el-option label="Aktiv" value="Aktiv" />
        <el-option label="Passiv" value="Passiv" />
        <el-option label="Ehrenmitglied" value="Ehrenmitglied" />
      </el-select>
    </el-form-item>

    <el-form-item label="Notes">
      <el-input type="textarea" :rows="3" :model-value="modelValue.notes ?? ''"
        @update:model-value="set('notes', $event || null)" :disabled="disabled" />
    </el-form-item>

    <template v-if="fields && fields.length > 0">
      <el-divider />
      <h3 style="margin-bottom:12px">Custom Fields</h3>
      <el-form-item v-for="f in fields" :key="f.id" :label="f.name + (f.required ? ' *' : '')">
        <el-select v-if="f.field_type === 'enum'"
          :model-value="cf[f.name] as string ?? ''"
          @update:model-value="setCf(f.name, $event || null)"
          :disabled="disabled" clearable>
          <el-option v-for="opt in f.options" :key="opt.id" :label="opt.value" :value="opt.value" />
        </el-select>
        <el-checkbox v-else-if="f.field_type === 'boolean'"
          :model-value="!!cf[f.name]"
          @update:model-value="setCf(f.name, $event)"
          :disabled="disabled" />
        <el-input v-else
          :type="f.field_type === 'number' ? 'number' : f.field_type === 'date' ? 'date' : 'text'"
          :model-value="cf[f.name] as string ?? ''"
          @update:model-value="setCf(f.name, $event || null)"
          :disabled="disabled" />
      </el-form-item>
    </template>
  </el-form>
</template>

// frontend/src/components/MemberForm.tsx
// frontend/src/components/MemberForm.tsx
import { useQuery } from '@tanstack/react-query'
import { getFieldDefinitions } from '../api/fieldDefinitions'
import type { Member, MembershipType } from '../types'

interface Props {
  value: Partial<Member>
  onChange: (updated: Partial<Member>) => void
  disabled?: boolean
}

export function MemberForm({ value, onChange, disabled }: Props) {
  const { data: fields = [] } = useQuery({ queryKey: ['field-definitions'], queryFn: getFieldDefinitions })

  const set = (key: keyof Member, val: unknown) => onChange({ ...value, [key]: val })
  const cf = value.custom_fields as Record<string, unknown> ?? {}
  const setCf = (name: string, val: unknown) => set('custom_fields', { ...cf, [name]: val })

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium mb-1">First Name *</label>
          <input required disabled={disabled} className="border rounded w-full px-3 py-2"
            value={value.first_name ?? ''} onChange={e => set('first_name', e.target.value)} />
        </div>
        <div>
          <label className="block text-sm font-medium mb-1">Last Name *</label>
          <input required disabled={disabled} className="border rounded w-full px-3 py-2"
            value={value.last_name ?? ''} onChange={e => set('last_name', e.target.value)} />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium mb-1">Email</label>
          <input type="email" disabled={disabled} className="border rounded w-full px-3 py-2"
            value={value.email ?? ''} onChange={e => set('email', e.target.value || null)} />
        </div>
        <div>
          <label className="block text-sm font-medium mb-1">Phone</label>
          <input disabled={disabled} className="border rounded w-full px-3 py-2"
            value={value.phone ?? ''} onChange={e => set('phone', e.target.value || null)} />
        </div>
      </div>
      <div>
        <label className="block text-sm font-medium mb-1">Membership Type *</label>
        <select required disabled={disabled} className="border rounded px-3 py-2"
          value={value.membership_type ?? ''} onChange={e => set('membership_type', e.target.value as MembershipType)}>
          <option value="">Select...</option>
          <option value="Aktiv">Aktiv</option>
          <option value="Passiv">Passiv</option>
          <option value="Ehrenmitglied">Ehrenmitglied</option>
        </select>
      </div>
      <div>
        <label className="block text-sm font-medium mb-1">Notes</label>
        <textarea disabled={disabled} className="border rounded w-full px-3 py-2" rows={3}
          value={value.notes ?? ''} onChange={e => set('notes', e.target.value || null)} />
      </div>

      {fields.length > 0 && (
        <div className="border-t pt-4">
          <h3 className="font-medium mb-3">Custom Fields</h3>
          <div className="space-y-3">
            {fields.map(f => (
              <div key={f.id}>
                <label className="block text-sm font-medium mb-1">{f.name}{f.required && ' *'}</label>
                {f.field_type === 'enum' ? (
                  <select disabled={disabled} className="border rounded px-3 py-2 w-full"
                    value={cf[f.name] as string ?? ''}
                    onChange={e => setCf(f.name, e.target.value || null)}>
                    <option value="">Select...</option>
                    {f.options.map(opt => (
                      <option key={opt.id} value={opt.value}>{opt.value}</option>
                    ))}
                  </select>
                ) : f.field_type === 'boolean' ? (
                  <input type="checkbox" disabled={disabled}
                    checked={!!cf[f.name]}
                    onChange={e => setCf(f.name, e.target.checked)} />
                ) : (
                  <input
                    type={f.field_type === 'number' ? 'number' : f.field_type === 'date' ? 'date' : 'text'}
                    disabled={disabled} className="border rounded w-full px-3 py-2"
                    value={cf[f.name] as string ?? ''}
                    onChange={e => setCf(f.name, e.target.value || null)} />
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
