// frontend/src/components/PresenceIndicator.vue
<script setup lang="ts">
import { usePresence } from '../composables/usePresence'

const props = defineProps<{ memberId: string }>()
const { viewers } = usePresence(props.memberId)
</script>

<template>
  <div v-if="viewers.length > 0" style="display:flex;gap:4px;align-items:center">
    <el-tag v-for="viewer in viewers" :key="viewer" size="small" type="info">
      {{ viewer }}
    </el-tag>
  </div>
</template>

// frontend/src/components/PresenceIndicator.tsx
import { usePresence } from '../hooks/usePresence'

export function PresenceIndicator({ memberId }: { memberId: string }) {
  const viewers = usePresence(memberId)
  if (viewers.length === 0) return null

  return (
    <div className="flex items-center gap-1 text-sm text-gray-500">
      <span className="w-2 h-2 rounded-full bg-green-400 inline-block" />
      {viewers.length === 1 ? `${viewers[0]} is also viewing` : `${viewers.length} others viewing`}
    </div>
  )
}
